modLoader = "javafml"
loaderVersion = "[4,)"
license = "All Rights Reserved"
issueTrackerURL = "https://github.com/ellie-mcquinn/storage-options/issues"

[[mods]]
modId = "storageoptions"
version = "${version}"
displayName = "Ellie's Storage Options"
updateJSONURL="https://api.modrinth.com/updates/ellies-storage-options/forge_updates.json?neoforge=only"
displayURL = "https://modrinth.com/project/ellies-storage-options"
logoFile = "storageoptions.png"
logoBlur = false

authors = "Ellie McQuinn"
credits = "mpustovoi"
description = "Adds some useful and pretty storage options ^_^"

[[dependencies.storageoptions]]
modId = "neoforge"
type = "required"
versionRange = "[${neoforge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.storageoptions]]
modId = "minecraft"
type = "required"
versionRange = "${nf_minecraft_constraint}"
ordering = "NONE"
side = "BOTH"

[[dependencies.storageoptions]]
modId = "kotlinforforge"
type = "required"
versionRange = "[${neoforge_kotlin_version},)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "storagelibrary-common.mixins.json"

[[mixins]]
config = "storagelibrary-neoforge.mixins.json"
