modLoader = "javafml"
loaderVersion = "[4,)"
license = "All Rights Reserved"
issueTrackerURL = "https://github.com/ellie-mcquinn/storage-mods/issues"

[[mods]]
modId = "storagemetallum"
version = "${version}"
displayName = "Ellie's Storage Metallum"
updateJSONURL="https://api.modrinth.com/updates/ellies-storage-metallum/forge_updates.json?neoforge=only"
displayURL = "https://modrinth.com/project/ellies-storage-metallum"
logoFile = "storagemetallum.png"
logoBlur = false

authors = "Ellie McQuinn"
description = "Adds some useful storage infused with metallum."

[[dependencies.storagemetallum]]
modId = "neoforge"
type = "required"
versionRange = "[${neoforge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.storagemetallum]]
modId = "minecraft"
type = "required"
versionRange = "${nf_minecraft_constraint}"
ordering = "NONE"
side = "BOTH"

[[dependencies.storagemetallum]]
modId = "kotlinforforge"
type = "required"
versionRange = "[${neoforge_kotlin_version},)"
ordering = "NONE"
side = "BOTH"
